### ISSUE TITLE
NoClassDefFoundError: com/fasterxml/jackson/core/util/RecyclerPool in version 4.5.2

### ISSUE THREAD

**Issue by rubensa** [eclipse-vertx/vertx-json-schema#127]
### Version

4.5.2 (works on 4.5.1 and 4.5.0)

### Context

Spring Boot 3.2.2 application with Jackson 2.15.3

I get the exception (only relevant lines shown):

```
java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.json.Json
 at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:1250)
 at io.vertx.core.json.JsonObject.(JsonObject.java:51)
 at org.eu.rubensa.mgmt.service.JsonSchemaValidationService.validate(JsonSchemaValidationService.java:37)
 at org.eu.rubensa.mgmt.service.JsonSchemaValidationServiceTest.validate_shouldReturnFalse_forAJsonValueThatDoNotSatisfiesTheSpecifiedSchema(JsonSchemaValidationServiceTest.java:157)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/RecyclerPool [in thread "main"]
 at io.vertx.core.json.jackson.JacksonFactory.(JacksonFactory.java:31)
 at io.vertx.core.spi.Utils.load(Utils.java:18)
 at io.vertx.core.spi.JsonFactory.load(JsonFactory.java:38)
 at io.vertx.core.json.Json.load(Json.java:38)
 at io.vertx.core.json.Json.(Json.java:28)
 at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:1250)
 at io.vertx.core.json.JsonObject.(JsonObject.java:51)
 at org.eu.rubensa.mgmt.service.JsonSchemaValidationService.validate(JsonSchemaValidationService.java:37)
 at org.eu.rubensa.mgmt.service.JsonSchemaValidationServiceTest.validate_shouldReturnTrue_forAJsonValueThatSatisfiesTheSpecifiedSchema(JsonSchemaValidationServiceTest.java:128)
 ... 3 more
```

**Comment by rubensa** [comment]
This is related to https://github.com/vert-x3/vertx-dependencies/commit/2e384513b564469acb9a1fb1f004c5c5500ab953

I was able to pass the test by "forcing" my project to update to Jackson 2.16.1 (but I'm not sure if this might affect other parts).

In pom.xml
```xml
...
  <properties>
    <jackson.version>2.16.1</jackson.version>
    ...
  </properties>
  ...
  <dependencyManagement>
    <dependencies>
      <!-- jackson -->
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      ...
    </dependencies>
  </dependencyManagement>
...
```

**Comment by rubensa** [comment]
"Forcing" my project to update to Jackson 2.16.1 breaks my app (the AbstractJackson2HttpMessageConverter fails reading Java types) :(

**Comment by vietj** [comment]
let me look if we can get away from the JacksonFactory if that is not present

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/5085

**Comment by rubensa** [comment]
Great!!  Thanks @vietj
